### ISSUE TITLE
Добавьте .gitignore

### ISSUE THREAD

**Issue by MarinaPaley** [Gladiaturuss/Introduction-PL#2]

**Comment by MarinaPaley** [comment]
Добавление `README.md` – это прекрасно, но не отменяет добавления `.gitignore`. Для его формирования можно воспользоваться ресурсом [gitignore.io](http://gitignore.io).

**Comment by Gladiaturuss** [comment]
.gitignore Создан и отображается в вкладке code
Я что-то делаю не так?

**Comment by MarinaPaley** [comment]
Push-и
